FROM python:latest

COPY ../common-lib/ common_lib/
RUN pip install -r common_lib/requirements.txt

COPY capture/requirements.txt .
RUN pip install -r requirements.txt

COPY capture/capturedata.py .

CMD ["python", "./capturedata.py" ]
