FROM python:latest

COPY ../common-lib/ common_lib/
RUN pip install -r common_lib/requirements.txt

COPY api/requirements.txt .
RUN pip install -r requirements.txt

COPY api/api.py .

CMD [ "python", "./api.py" ]
